#!/usr/bin/env python3
"""IKP Estimate — estimate a model's effective parameter count via factual knowledge probing.

Runs the IKP benchmark against a model and estimates its IKP-effective
parameter count (N_eff): the size of a calibration-cohort-average open model
with equal incompressible-knowledge capacity, from the curve fitted on the
open-weight cohort (135M to 1.6T). N_eff equals the true weight count only
up to the model's knowledge density ρ ≡ N_eff/N_true — see PARAM_POLICY.md.

Usage:
  # Estimate via OpenRouter
  python scripts/ikp_estimate.py --model openai/gpt-4.1

  # Estimate via custom OpenAI-compatible API
  python scripts/ikp_estimate.py --api-base http://localhost:8000/v1 --model my-model

  # Use a sample (faster, less accurate)
  python scripts/ikp_estimate.py --model openai/gpt-4.1 --sample 200

  # Inspect results: show all questions, answers, and verdicts
  python scripts/ikp_estimate.py --model openai/gpt-4.1 --inspect

  # Just inspect the probe set (no model query)
  python scripts/ikp_estimate.py --inspect-probes

  # Show calibration info
  python scripts/ikp_estimate.py --show-calibration
"""

import argparse
import json
import math
import os
import random
import re
import sys
import time
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from urllib.parse import urlparse

import httpx

# ── Constants ──────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).parent.parent
PROBE_FILE = PROJECT_ROOT / "data" / "probes" / "final_probe_set_v8.json"
SYSTEM_MSG = "Answer factual questions directly and concisely. If you don't know, say 'I don't know'."
JUDGE_MODEL = "google/gemini-3-flash-preview"
OPENCODE_GO_USER_AGENT = "amatouhake-ikp/0.1 (+https://github.com/amatouhake/ikp)"
HALLUCINATION_PENALTY = 0.0  # no penalty: wrong answers score the same as refusals (λ=0)
TIERS = ["T1", "T2", "T3", "T4", "T5", "T6", "T7"]
API_STYLES = ("chat", "responses")
REASONING_EFFORTS = ("default", "low", "medium", "high", "xhigh")
DEFAULT_SAMPLE_SEED = 42
MAX_API_ATTEMPTS = 3
RETRY_BACKOFF_SECONDS = 3

# Calibration curve. The single source of truth for effective-parameter
# estimates is data/results/effective_params.json, stored as
#   accuracy = a · log10(params_B) + b   (λ=0, no penalty)
# which we invert to  log10(params_B) = CALIB_SLOPE · accuracy + CALIB_INTERCEPT.
# We load it at runtime (falling back to the last known fit) so this tool, the
# analysis scripts and both estimator versions use one calibration. Regenerate
# the artifact with scripts/19_effective_params.py after changing the cohort.
CALIB_FILE = PROJECT_ROOT / "data" / "results" / "calibration_refit_v2.json"
EFFECTIVE_PARAMS_FILE = PROJECT_ROOT / "data" / "results" / "effective_params.json"


class APIRequestError(RuntimeError):
    """An API failure that must never be converted into a benchmark verdict."""

    def __init__(self, message: str, status_code: int | None = None):
        super().__init__(message)
        self.status_code = status_code


class TargetAPIError(APIRequestError):
    """The target model request failed or returned an unusable response."""


class JudgeAPIError(APIRequestError):
    """The fixed benchmark judge request failed or returned an unusable response."""


def _load_calibration():
    a, b, n, r2 = 0.15878, 0.24226, 93, 0.9105
    try:
        row = json.load(open(EFFECTIVE_PARAMS_FILE))["calibration"]
        a, b = row["slope"], row["intercept"]
        n, r2 = row["n"], row["r_squared"]
    except Exception:
        try:
            d = json.load(open(CALIB_FILE))
            row = next((r for r in d.get("sensitivity_sweep", [])
                        if abs(r.get("lambda", 9)) < 1e-9), None)
            if row:
                a, b = row["slope"], row["intercept"]
                n, r2 = row["n"], row["r_squared"]
        except Exception:
            pass
    return (1.0 / a, -b / a, n, r2, a, b)


CALIB_SLOPE, CALIB_INTERCEPT, CALIB_N, CALIB_R2, ACC_SLOPE, ACC_INTERCEPT = _load_calibration()

# 90% prediction band, leave-one-FAMILY-out CV (the honest band for a new
# vendor — see PARAM_POLICY.md §2). Regenerated by scripts/19_effective_params.py.
def _load_lofo_band():
    try:
        d = json.load(open(EFFECTIVE_PARAMS_FILE))
        return float(d["cross_validation"]["lofo"]["pi90_fold"])
    except Exception:
        return 3.51  # last known LOFO 90% PI


LOFO_PI90 = _load_lofo_band()

# Tier boundary descriptions
TIER_INFO = {
    "T1": {"range": "< 1B",    "desc": "Universal knowledge — known by the smallest models"},
    "T2": {"range": "1B–7B",   "desc": "Common reference knowledge"},
    "T3": {"range": "7B–32B",  "desc": "Domain-specific knowledge"},
    "T4": {"range": "32B–235B", "desc": "Specialized knowledge"},
    "T5": {"range": "235B–1T", "desc": "Deep knowledge — requires frontier-scale models"},
    "T6": {"range": "1T–5T",   "desc": "Long-tail knowledge — only the largest models"},
    "T7": {"range": "> 5T",    "desc": "Extreme long-tail — beyond current model capacity"},
}


# ── Helpers ────────────────────────────────────────────────────
def strip_thinking(text: str) -> str:
    if not text:
        return ""
    # Reasoning is a separate field in the Responses API and must not be
    # scored.  Some chat-compatible providers still wrap it in <think> tags;
    # remove complete and truncated blocks without falling back to the block.
    cleaned = re.sub(r'<think>.*?</think>', '', text,
                     flags=re.DOTALL | re.IGNORECASE)
    cleaned = re.sub(r'<think>.*$', '', cleaned,
                     flags=re.DOTALL | re.IGNORECASE)
    return cleaned.strip()


def estimate_params(accuracy: float) -> float:
    """Estimate effective parameter count (N_eff, billions) from λ=0 accuracy."""
    if accuracy <= 0:
        return 0
    log_b = CALIB_SLOPE * accuracy + CALIB_INTERCEPT
    return 10 ** log_b


def format_params(b: float) -> str:
    """Format parameter count for display."""
    if b <= 0:
        return "N/A"
    if b < 1:
        return f"{b * 1000:.0f}M"
    if b < 1000:
        return f"{b:.0f}B"
    return f"{b / 1000:.1f}T"


def refusal_summary(tier_stats: dict) -> dict:
    """Compute the v2 refusal interval and confidence for the default report."""
    observed = adjusted = 0.0
    total = refusals = 0
    for t in ["T1", "T2", "T3", "T4", "T5", "T6", "T7"]:
        s = tier_stats.get(t, {})
        n = s.get("total", 0)
        if not n:
            continue
        observed += s.get("correct", 0) / n
        attempted = s.get("correct", 0) + s.get("wrong", 0)
        adjusted += (s.get("correct", 0) / attempted if attempted
                     else s.get("correct", 0) / n)
        total += n
        refusals += s.get("refusal", 0)
    rate = refusals / total if total else 0.0
    confidence = ("Reliable" if rate < 0.10 else
                  "Caution" if rate < 0.30 else "Low confidence")
    acc_observed = observed / 7
    acc_adjusted = adjusted / 7
    return {
        "refusal_rate": rate,
        "confidence": confidence,
        "accuracy_observed": acc_observed,
        "accuracy_adjusted": acc_adjusted,
        "n_eff_floor_B": estimate_params(acc_observed),
        "n_eff_adjusted_B": estimate_params(acc_adjusted),
    }


# ── Model query ────────────────────────────────────────────────
def effective_reasoning_effort(is_thinking: bool = False,
                               reasoning_effort: str = "default") -> str:
    """Resolve the new effort option while retaining --thinking semantics."""
    if reasoning_effort is None:
        reasoning_effort = "default"
    if reasoning_effort not in REASONING_EFFORTS:
        raise ValueError(
            f"reasoning_effort must be one of {', '.join(REASONING_EFFORTS)}"
        )
    if is_thinking and reasoning_effort == "default":
        return "medium"
    return reasoning_effort


def build_target_request(api_base: str, model: str, question: str,
                         api_style: str = "chat",
                         reasoning_effort: str = "default",
                         is_thinking: bool = False) -> tuple[str, dict]:
    """Build one target request without adding authentication headers."""
    if api_style not in API_STYLES:
        raise ValueError(f"api_style must be one of {', '.join(API_STYLES)}")
    effort = effective_reasoning_effort(is_thinking, reasoning_effort)

    if api_style == "responses":
        # This is the Responses API shape: instructions carries the system
        # message and input is an explicit user message, rather than a
        # chat-completions `messages` array.
        payload = {
            "model": model,
            "instructions": SYSTEM_MSG,
            "input": [{
                "role": "user",
                "content": [{"type": "input_text", "text": question}],
            }],
        }
        if effort != "default":
            payload["reasoning"] = {"effort": effort}
        return f"{api_base.rstrip('/')}/responses", payload

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_MSG},
            {"role": "user", "content": question},
        ],
        "temperature": 0,
    }
    if effort != "default":
        payload["reasoning"] = {"effort": effort}
    return f"{api_base.rstrip('/')}/chat/completions", payload


def target_request_preview(api_base: str, model: str,
                           api_style: str = "chat",
                           reasoning_effort: str = "default",
                           is_thinking: bool = False,
                           has_api_key: bool = False) -> dict:
    """Return a safe request preview; it never contains an API key."""
    endpoint, payload = build_target_request(
        api_base, model, "<question>", api_style, reasoning_effort, is_thinking
    )
    headers = {"Content-Type": "application/json"}
    if _is_opencode_go_base(api_base):
        headers["User-Agent"] = OPENCODE_GO_USER_AGENT
    if has_api_key:
        headers["Authorization"] = "Bearer <redacted>"
    return {
        "method": "POST",
        "url": endpoint,
        "headers": headers,
        "payload": payload,
    }


def extract_chat_text(data: dict) -> str:
    """Extract final chat text without falling back to reasoning fields."""
    choices = data.get("choices")
    if not isinstance(choices, list) or not choices:
        return ""
    choice = choices[0]
    if not isinstance(choice, dict):
        return ""
    message = choice.get("message")
    if not isinstance(message, dict):
        return ""

    content = message.get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, dict):
        text = content.get("text")
        return text if isinstance(text, str) else ""
    if isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, str):
                parts.append(part)
            elif isinstance(part, dict) and part.get("type") in ("text", "output_text"):
                text = part.get("text")
                if isinstance(text, str):
                    parts.append(text)
        if parts:
            return "".join(parts)

    # Chat APIs can represent a genuine refusal separately from content. It
    # is model output and should remain judgeable, unlike reasoning content.
    refusal = message.get("refusal")
    return refusal if isinstance(refusal, str) else ""


def extract_responses_text(data: dict) -> str:
    """Extract final assistant text while ignoring Responses reasoning items."""
    output_text = data.get("output_text")
    if isinstance(output_text, str) and output_text.strip():
        return output_text

    output = data.get("output")
    if not isinstance(output, list):
        return ""

    final_parts = []
    for item in output:
        if not isinstance(item, dict) or item.get("type") != "message":
            continue
        if item.get("role") not in (None, "assistant"):
            continue
        content = item.get("content")
        if isinstance(content, str):
            final_parts.append(content)
            continue
        if isinstance(content, dict):
            content = [content]
        if not isinstance(content, list):
            continue
        for part in content:
            if isinstance(part, str):
                final_parts.append(part)
                continue
            if not isinstance(part, dict):
                continue
            part_type = part.get("type")
            if part_type in ("output_text", "text"):
                text = part.get("text")
            elif part_type == "refusal":
                text = part.get("refusal") or part.get("text")
            else:
                # In particular, do not traverse reasoning summaries or
                # reasoning content looking for a plausible answer.
                text = None
            if isinstance(text, str):
                final_parts.append(text)
    return "\n".join(part for part in final_parts if part)


def _post_json(http, url: str, headers: dict, payload: dict,
               error_type: type[APIRequestError], sleep_fn=None) -> dict:
    """POST JSON with bounded retries for transient transport failures."""
    sleep_fn = time.sleep if sleep_fn is None else sleep_fn
    last_error = "request failed"
    last_status = None

    for attempt in range(MAX_API_ATTEMPTS):
        try:
            response = http.post(url, headers=headers, json=payload)
        except httpx.HTTPError as exc:
            last_error = f"network failure ({type(exc).__name__})"
            if attempt + 1 < MAX_API_ATTEMPTS:
                sleep_fn(RETRY_BACKOFF_SECONDS * (attempt + 1))
            continue

        status = response.status_code
        last_status = status
        if 200 <= status < 300:
            try:
                data = response.json()
            except (TypeError, ValueError) as exc:
                raise error_type(
                    f"HTTP {status} returned invalid JSON ({type(exc).__name__})",
                    status,
                ) from exc
            if not isinstance(data, dict):
                raise error_type(f"HTTP {status} returned a non-object JSON response",
                                 status)
            if data.get("error") is not None:
                raise error_type("server returned an API error", status)
            return data

        last_error = f"HTTP {status}"
        if status == 429 or 500 <= status <= 599:
            if attempt + 1 < MAX_API_ATTEMPTS:
                sleep_fn(RETRY_BACKOFF_SECONDS * (attempt + 1))
            continue
        raise error_type(last_error, status)

    raise error_type(last_error, last_status)


def make_query_fn(api_base: str, api_key: str, model: str,
                  is_thinking: bool = False, api_style: str = "chat",
                  reasoning_effort: str = "default", client_factory=None,
                  sleep_fn=None):
    """Create a target query function for chat or Responses APIs."""
    effort = effective_reasoning_effort(is_thinking, reasoning_effort)
    client_factory = httpx.Client if client_factory is None else client_factory

    def query(question: str) -> str:
        endpoint, payload = build_target_request(
            api_base, model, question, api_style, effort
        )
        headers = {"Content-Type": "application/json"}
        if _is_opencode_go_base(api_base):
            headers["User-Agent"] = OPENCODE_GO_USER_AGENT
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        with client_factory(timeout=120) as http:
            data = _post_json(http, endpoint, headers, payload,
                              TargetAPIError, sleep_fn)

        if api_style == "responses":
            content = extract_responses_text(data)
        else:
            content = extract_chat_text(data)
        content = strip_thinking(content)
        if not content.strip():
            raise TargetAPIError("successful response contained no final textual output")
        return content

    query.api_style = api_style
    query.reasoning_effort = effort
    query.endpoint = f"{api_base.rstrip('/')}/{('responses' if api_style == 'responses' else 'chat/completions')}"
    return query


def make_judge_fn(api_key: str, client_factory=None, sleep_fn=None):
    """Create judge function using the fixed OpenRouter judge."""
    client_factory = httpx.Client if client_factory is None else client_factory

    def judge(question: str, gold: str, response: str) -> str:
        if not response or not response.strip():
            return "REFUSAL"

        if ';' in gold:
            gold_display = ' OR '.join(a.strip() for a in gold.split(';'))
            co_note = "\nNOTE: Any of the listed names counts as CORRECT."
        else:
            gold_display = gold
            co_note = ""

        prompt = f"""You are a strict factual judge. Classify the model's response.

Question: {question}
Correct answer: {gold_display}
Model's response: {response}

Rules:
1. YEAR must match exactly. 2. NUMBER within 1-2%. 3. NAME: same entity, minor spelling OK.
4. RESEARCH FIELD: accept adjacent/related subfields. Multiple unrelated guesses = WRONG.
5. If refuses or doesn't know: REFUSAL. 6. Different answer: WRONG.
{co_note}
Reply one word: CORRECT, REFUSAL, or WRONG"""

        headers = {"Content-Type": "application/json"}
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
        payload = {"model": JUDGE_MODEL,
                   "messages": [{"role": "user", "content": prompt}],
                   "temperature": 0,
                   "reasoning": {"effort": "low"}}

        with client_factory(timeout=60) as http:
            data = _post_json(
                http, "https://openrouter.ai/api/v1/chat/completions",
                headers, payload, JudgeAPIError, sleep_fn
            )

        choices = data.get("choices")
        if not isinstance(choices, list) or not choices:
            raise JudgeAPIError("successful response contained no judge choice")
        message = choices[0].get("message") if isinstance(choices[0], dict) else None
        raw = message.get("content") if isinstance(message, dict) else None
        if not isinstance(raw, str) or not raw.strip():
            raise JudgeAPIError("successful response contained no judge text")
        raw = raw.strip()
        if raw in ("CORRECT", "REFUSAL", "WRONG"):
            return raw
        raise JudgeAPIError(f"unrecognized judge verdict: {raw[:80]!r}")

    return judge


def stratified_sample(probes: list, sample_size: int,
                      seed: int = DEFAULT_SAMPLE_SEED) -> list:
    """Select exactly sample_size probes, balanced across the seven tiers."""
    if sample_size is None:
        return list(probes)
    if sample_size < 0:
        raise ValueError("sample size must be non-negative")
    if sample_size > len(probes):
        raise ValueError(
            f"sample size {sample_size} exceeds the {len(probes)} available probes"
        )
    if sample_size == 0:
        return []

    by_tier = {tier: [] for tier in TIERS}
    for probe in probes:
        if probe.get("tier") in by_tier:
            by_tier[probe["tier"]].append(probe)
    available = sum(len(items) for items in by_tier.values())
    if sample_size > available:
        raise ValueError("sample requires probes outside the T1..T7 tiers")

    rng = random.Random(seed)
    remaining_by_tier = {}
    selected_by_tier = {}
    base, remainder = divmod(sample_size, len(TIERS))
    requested = {
        tier: base + (index < remainder)
        for index, tier in enumerate(TIERS)
    }

    for tier in TIERS:
        candidates = list(by_tier[tier])
        rng.shuffle(candidates)
        take = min(requested[tier], len(candidates))
        selected_by_tier[tier] = candidates[:take]
        remaining_by_tier[tier] = candidates[take:]

    deficit = sample_size - sum(len(items) for items in selected_by_tier.values())
    while deficit:
        eligible = [
            tier for tier in TIERS
            if remaining_by_tier[tier]
        ]
        if not eligible:
            raise ValueError("not enough tiered probes to satisfy sample size")
        # Fill a short tier first, with tier order as the deterministic tie-break.
        tier = min(eligible, key=lambda item: (len(selected_by_tier[item]),
                                               TIERS.index(item)))
        selected_by_tier[tier].append(remaining_by_tier[tier].pop())
        deficit -= 1

    return [probe for tier in TIERS for probe in selected_by_tier[tier]]


def _is_openrouter_base(api_base: str) -> bool:
    try:
        parsed = urlparse(api_base)
    except ValueError:
        return False
    return parsed.scheme in ("http", "https") and parsed.hostname == "openrouter.ai"


def _is_opencode_go_base(api_base: str) -> bool:
    try:
        parsed = urlparse(api_base)
    except ValueError:
        return False
    path = parsed.path.rstrip("/")
    return (
        parsed.scheme in ("http", "https")
        and parsed.hostname == "opencode.ai"
        and (path == "/zen/go" or path.startswith("/zen/go/"))
    )


def resolve_target_api_key(api_base: str, explicit_api_key: str | None) -> str:
    """Resolve only the target credential; never use it for the judge."""
    if explicit_api_key is not None:
        return explicit_api_key
    if _is_opencode_go_base(api_base):
        return os.environ.get("OPENCODE_GO_API_KEY", "")
    if _is_openrouter_base(api_base):
        return os.environ.get("OPENROUTER_API_KEY", "")
    return os.environ.get("IKP_TARGET_API_KEY", "")


# ── Display ────────────────────────────────────────────────────
VERDICT_COLORS = {
    "CORRECT": "\033[92m",  # green
    "WRONG": "\033[91m",    # red
    "REFUSAL": "\033[93m",  # yellow
}
RESET = "\033[0m"
DIM = "\033[90m"


def display_results(model_name: str, results: list, tier_accs: dict, accuracy: float,
                    raw_accuracy: float, estimated_B: float,
                    refusal: dict, inspect: bool):
    """Display evaluation results."""
    print()
    print(f"  ╔══════════════════════════════════════════════════════════╗")
    print(f"  ║  IKP Estimation Results                                 ║")
    print(f"  ╠══════════════════════════════════════════════════════════╣")
    print(f"  ║  Model:     {model_name:42s}  ║")
    print(f"  ║  Probes:    {len(results):<42d}  ║")
    print(f"  ║  Accuracy:  {accuracy:.1%} (λ=0, no penalty; raw {raw_accuracy:.1%}){' ' * 4}  ║")
    print(f"  ║  N_eff:    ~{format_params(estimated_B):>6s} effective parameters{' ' * 16}  ║")
    print(f"  ╚══════════════════════════════════════════════════════════╝")

    # Per-tier breakdown
    print(f"\n  {'Tier':<5} {'Accuracy':>9} {'Correct':>8} {'Wrong':>7} {'Refuse':>7} {'Total':>6}  Description")
    print(f"  {'─' * 80}")
    for t in ["T1", "T2", "T3", "T4", "T5", "T6", "T7"]:
        tier_results = [r for r in results if r["tier"] == t]
        if not tier_results:
            continue
        correct = sum(1 for r in tier_results if r["verdict"] == "CORRECT")
        wrong = sum(1 for r in tier_results if r["verdict"] == "WRONG")
        refusal_count = sum(1 for r in tier_results if r["verdict"] == "REFUSAL")
        total = len(tier_results)
        acc = tier_accs.get(t, 0)
        info = TIER_INFO.get(t, {})
        marker = " ◀ frontier" if acc > 0 and t in ["T5", "T6", "T7"] else ""
        print(f"  {t:<5} {acc:>8.0%} {correct:>8} {wrong:>7} {refusal_count:>7} {total:>6}  "
              f"{DIM}{info.get('range', '')}: {info.get('desc', '')}{RESET}{marker}")

    # Determine effective tier
    effective_tier = "T1"
    for t in ["T7", "T6", "T5", "T4", "T3", "T2", "T1"]:
        if tier_accs.get(t, 0) > 0.05:
            effective_tier = t
            break

    print(f"\n  Effective tier: {effective_tier} ({TIER_INFO[effective_tier]['desc']})")
    print(f"  Effective size: ~{format_params(estimated_B)} IKP-effective parameters "
          f"(calibrated on {CALIB_N} open models, R²={CALIB_R2:.3f})")
    print(f"  Refusal interval: {format_params(refusal['n_eff_floor_B'])} – "
          f"{format_params(refusal['n_eff_adjusted_B'])} "
          f"({refusal['refusal_rate']:.1%} refusals; {refusal['confidence']})")
    if estimated_B > 0:
        print(f"  90% band (new-vendor LOFO): "
              f"{format_params(estimated_B / LOFO_PI90)} – "
              f"{format_params(estimated_B * LOFO_PI90)}")
    print(f"  {DIM}N_eff is the open-cohort-equivalent size, not the true weight "
          f"count — see PARAM_POLICY.md.{RESET}")

    # Confidence note
    if len(results) < 200:
        print(f"\n  {DIM}⚠ Using {len(results)} probes (sampled). For more precise estimates, "
              f"use the full 1400-probe set.{RESET}")
    print()

    # Inspect mode: show all probes
    if inspect:
        print(f"  {'─' * 90}")
        print(f"  DETAILED RESULTS")
        print(f"  {'─' * 90}")
        for t in ["T1", "T2", "T3", "T4", "T5", "T6", "T7"]:
            tier_results = [r for r in results if r["tier"] == t]
            if not tier_results:
                continue
            print(f"\n  {DIM}── {t} ──{RESET}")
            for r in tier_results:
                color = VERDICT_COLORS.get(r["verdict"], "")
                symbol = {"CORRECT": "✓", "WRONG": "✗", "REFUSAL": "?"}.get(r["verdict"], "-")
                print(f"  {color}{symbol}{RESET} Q: {r['question']}")
                print(f"    Gold: {r['gold_answer']}")
                if r["response"]:
                    print(f"    Model: {r['response']}")
                print(f"    Verdict: {color}{r['verdict']}{RESET}")
                print()


def display_probes(probes: list):
    """Display probe set for inspection."""
    from collections import Counter
    tier_counts = Counter(p["tier"] for p in probes)
    domain_counts = Counter(p.get("domain", "?") for p in probes)

    print(f"\n  IKP Probe Set v8: {len(probes)} probes")
    print(f"\n  Per tier:")
    for t in sorted(tier_counts):
        info = TIER_INFO.get(t, {})
        print(f"    {t}: {tier_counts[t]:>4} probes  ({info.get('range', '')}: {info.get('desc', '')})")

    print(f"\n  Top domains:")
    for domain, count in domain_counts.most_common(10):
        print(f"    {domain:30s} {count:>4}")

    print(f"\n  Sample probes by tier:")
    for t in ["T1", "T3", "T5", "T7"]:
        tier_probes = [p for p in probes if p["tier"] == t]
        print(f"\n  {DIM}── {t} ──{RESET}")
        for p in tier_probes[:3]:
            print(f"    Q: {p['question']}")
            print(f"    A: {p['answer']}")
            print()


def display_calibration():
    """Display calibration curve info."""
    print(f"\n  IKP Calibration Curve")
    print(f"  {'─' * 50}")
    print(f"  log₁₀(N_eff_B) = {CALIB_SLOPE:.4f} × accuracy + ({CALIB_INTERCEPT:.4f})")
    print(f"  Fitted on {CALIB_N} open-weight models (135M to 1.6T)")
    print(f"  R² = {CALIB_R2:.3f}")
    print(f"  90% new-vendor (LOFO) band: ×/÷ {LOFO_PI90:.2f}")
    print(f"  N_eff = IKP-effective parameters; see PARAM_POLICY.md")
    print(f"\n  Reference points:")

    reference = [
        (0.19, "~1B (e.g., Llama 3.2 1B)"),
        (0.28, "~3B (e.g., Llama 3.2 3B)"),
        (0.37, "~8B (e.g., Llama 3 8B)"),
        (0.44, "~24B (e.g., Mistral Small)"),
        (0.52, "~70B (e.g., Llama 3 70B)"),
        (0.63, "~670B (e.g., DeepSeek V3)"),
        (0.69, "~1T (e.g., Kimi K2.5)"),
    ]
    for acc, desc in reference:
        est = estimate_params(acc)
        print(f"    accuracy={acc:.0%}  →  {format_params(est):>6s}  {desc}")
    print()


# ── Main ──────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(
        description="IKP Estimate — estimate LLM parameter count via factual knowledge probing",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # Model specification
    model_group = parser.add_argument_group("Model")
    model_group.add_argument("--model", "-m", metavar="MODEL",
                             help="Model name (OpenRouter ID or custom model name)")
    model_group.add_argument("--api-base", metavar="URL",
                             default="https://openrouter.ai/api/v1",
                             help="API base URL (default: OpenRouter)")
    model_group.add_argument("--api-style", choices=API_STYLES, default="chat",
                             help="Target API style: chat (default) or responses")
    model_group.add_argument("--api-key", metavar="KEY",
                             help="Target API key (use OPENCODE_GO_API_KEY for Go)")
    model_group.add_argument("--thinking", action="store_true",
                             help="Backward-compatible alias for --reasoning-effort medium")
    model_group.add_argument("--reasoning-effort", choices=REASONING_EFFORTS,
                             default="default", metavar="EFFORT",
                             help="Target reasoning override: default, low, medium, high, xhigh")

    # Evaluation options
    eval_group = parser.add_argument_group("Evaluation")
    eval_group.add_argument("--sample", "-n", type=int, metavar="N",
                            help="Sample exactly N probes, balanced across T1..T7 (default: all)")
    eval_group.add_argument("--seed", type=int, default=DEFAULT_SAMPLE_SEED,
                            help=f"Sampling seed (default: {DEFAULT_SAMPLE_SEED})")
    eval_group.add_argument("--workers", "-w", type=int, default=16,
                            help="Parallel workers (default: 16)")
    eval_group.add_argument("--sequential", "-s", action="store_true",
                            help="Disable parallelism")
    eval_group.add_argument("--output", "-o", metavar="FILE",
                            help="Save detailed results to JSON file")

    # Display options
    display_group = parser.add_argument_group("Display")
    display_group.add_argument("--inspect", action="store_true",
                               help="Show detailed per-probe results")
    display_group.add_argument("--inspect-probes", action="store_true",
                               help="Inspect the probe set and exit")
    display_group.add_argument("--show-calibration", action="store_true",
                               help="Show calibration curve info and exit")
    display_group.add_argument("--request-preview", action="store_true",
                               help="Print a redacted target request preview and exit")

    args = parser.parse_args()
    requested_effort = effective_reasoning_effort(args.thinking, args.reasoning_effort)

    # This mode is deliberately evaluated before loading probes or resolving
    # environment variables, so it cannot make a network call or expose a key.
    if args.request_preview:
        print(json.dumps(
            target_request_preview(
                args.api_base, args.model or "<model>", args.api_style,
                args.reasoning_effort, args.thinking, bool(args.api_key)
            ),
            indent=2,
            ensure_ascii=False,
        ))
        return

    # Info-only modes
    if args.show_calibration:
        display_calibration()
        return

    probes = json.load(open(PROBE_FILE))

    if args.inspect_probes:
        display_probes(probes)
        return

    if not args.model:
        parser.print_help()
        return

    # Set up separate target and judge credentials. The target credential is
    # never used as a fallback for the fixed OpenRouter judge.
    api_key = resolve_target_api_key(args.api_base, args.api_key)
    if not api_key and (_is_openrouter_base(args.api_base) or
                        _is_opencode_go_base(args.api_base)):
        env_name = ("OPENCODE_GO_API_KEY" if _is_opencode_go_base(args.api_base)
                    else "OPENROUTER_API_KEY")
        print(f"Error: {env_name} not set for the target. Use --api-key or set the env var.")
        sys.exit(1)

    # Sample probes if requested. The local RNG keeps repeated seeds
    # independent of any other random use in this process.
    if args.sample is not None:
        try:
            probes = stratified_sample(probes, args.sample, args.seed)
        except ValueError as exc:
            parser.error(str(exc))
    selected_probe_ids = [probe.get("id", "") for probe in probes]

    # Check the judge credential before spending a target request.
    judge_key = os.environ.get("OPENROUTER_API_KEY", "")
    if not judge_key:
        print("  Error: OPENROUTER_API_KEY needed for the judge model. Set it as env var.")
        sys.exit(1)

    # Pre-test the model
    print(f"\n  Testing {args.model}...")
    query_fn = make_query_fn(
        args.api_base, api_key, args.model, args.thinking,
        args.api_style, args.reasoning_effort
    )
    try:
        test_resp = query_fn("What is the capital of France?")
    except TargetAPIError as exc:
        print(f"  Error: target API request failed; run aborted ({exc})",
              file=sys.stderr)
        sys.exit(1)
    if "paris" not in test_resp.lower():
        print(f"  Warning: unexpected test response: {test_resp[:100]}")
    else:
        print(f"  Model OK: {test_resp[:60]}")
    print(f"  Target transport: {args.api_style}; reasoning effort requested: {requested_effort}")
    if requested_effort != "default":
        print("  Note: reasoning effort is requested but not verified as active; "
              "confirm it with the canary response/provider behavior.")
    judge_fn = make_judge_fn(judge_key)

    # Run evaluation
    total = len(probes)
    print(f"\n  Running {total} probes ({args.workers} workers)...\n")

    results = []
    _lock = threading.Lock()
    _done = [0]

    def eval_one(probe):
        q = probe["question"]
        gold = probe["answer"]
        response = ""
        error_type = None
        error_message = None
        try:
            response = query_fn(q)
        except TargetAPIError as exc:
            error_type = "target_api"
            error_message = str(exc)
        if error_type is None:
            try:
                verdict = judge_fn(q, gold, response)
            except JudgeAPIError as exc:
                error_type = "judge_api"
                error_message = str(exc)
        if error_type is not None:
            verdict = "INFRASTRUCTURE_ERROR"

        with _lock:
            _done[0] += 1
            if _done[0] % 50 == 0 or _done[0] == total:
                correct_so_far = sum(1 for r in results if r.get("verdict") == "CORRECT")
                sys.stderr.write(f"\r  [{_done[0]}/{total}] {correct_so_far} correct")
                sys.stderr.flush()

        return {
            "probe_id": probe.get("id", ""),
            "tier": probe["tier"],
            "domain": probe.get("domain", ""),
            "question": q,
            "gold_answer": gold,
            "response": (response or "")[:500],
            "verdict": verdict,
            **({"error_type": error_type, "error": error_message}
               if error_type else {}),
        }

    workers = 1 if args.sequential else args.workers
    with ThreadPoolExecutor(max_workers=workers) as executor:
        futures = {executor.submit(eval_one, p): p for p in probes}
        for future in as_completed(futures):
            results.append(future.result())

    sys.stderr.write("\r" + " " * 60 + "\r")
    sys.stderr.flush()

    infrastructure_errors = [
        result for result in results
        if result.get("verdict") == "INFRASTRUCTURE_ERROR"
    ]
    if infrastructure_errors:
        print(
            f"Error: {len(infrastructure_errors)} infrastructure error(s); "
            "no estimate was computed or scored.",
            file=sys.stderr,
        )
        for result in infrastructure_errors[:3]:
            print(f"  {result['probe_id']}: {result['error_type']} - "
                  f"{result['error']}", file=sys.stderr)
        if args.output:
            failure_output = {
                "status": "failed",
                "error": "infrastructure_error",
                "model": args.model,
                "api_base": args.api_base,
                "api_style": args.api_style,
                "reasoning_effort": requested_effort,
                "reasoning_effort_requested": requested_effort,
                "reasoning_effort_verification": (
                    "not_requested" if requested_effort == "default"
                    else "requested_unverified"
                ),
                "seed": args.seed,
                "selected_probe_ids": selected_probe_ids,
                "target_request_preview": target_request_preview(
                    args.api_base, args.model, args.api_style,
                    args.reasoning_effort, args.thinking, bool(api_key)
                ),
                "infrastructure_errors": infrastructure_errors,
                "results": results,
            }
            output_path = Path(args.output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with output_path.open("w") as f:
                json.dump(failure_output, f, indent=2, ensure_ascii=False)
            print(f"  Failure details saved to {args.output}")
        sys.exit(1)

    # Compute scores
    from collections import defaultdict
    tier_stats = defaultdict(lambda: {"correct": 0, "total": 0, "refusal": 0, "wrong": 0})
    for r in results:
        t = r["tier"]
        tier_stats[t]["total"] += 1
        if r["verdict"] == "CORRECT":
            tier_stats[t]["correct"] += 1
        elif r["verdict"] == "REFUSAL":
            tier_stats[t]["refusal"] += 1
        else:
            tier_stats[t]["wrong"] += 1

    tier_accs = {}
    for t in ["T1", "T2", "T3", "T4", "T5", "T6", "T7"]:
        s = tier_stats[t]
        if s["total"] > 0:
            # Not floored at zero (matches the paper); moot at the default lambda=0.
            tier_accs[t] = (s["correct"] + HALLUCINATION_PENALTY * s["wrong"]) / s["total"]
        else:
            tier_accs[t] = 0.0

    accuracy = sum(tier_accs.values()) / len(tier_accs) if tier_accs else 0
    correct_total = sum(s["correct"] for s in tier_stats.values())
    raw_accuracy = correct_total / len(results) if results else 0
    estimated_B = estimate_params(accuracy)
    refusal = refusal_summary(tier_stats)

    # Display
    display_results(args.model, results, tier_accs, accuracy, raw_accuracy,
                    estimated_B, refusal, args.inspect)

    # Save if requested
    if args.output:
        output = {
            "status": "completed",
            "model": args.model,
            "api_base": args.api_base,
            "api_style": args.api_style,
            "reasoning_effort": requested_effort,
            "reasoning_effort_requested": requested_effort,
            "reasoning_effort_verification": (
                "not_requested" if requested_effort == "default"
                else "requested_unverified"
            ),
            "seed": args.seed,
            "selected_probe_ids": selected_probe_ids,
            "target_request_preview": target_request_preview(
                args.api_base, args.model, args.api_style,
                args.reasoning_effort, args.thinking, bool(api_key)
            ),
            "probes_used": len(results),
            "accuracy": accuracy,
            "raw_accuracy": raw_accuracy,
            "estimated_params_B": estimated_B,  # kept for compatibility; == n_eff_B
            "n_eff_B": estimated_B,
            "n_eff_band90_B": ([estimated_B / LOFO_PI90, estimated_B * LOFO_PI90]
                               if estimated_B > 0 else None),
            "refusal": refusal,
            "tier_accuracy": tier_accs,
            "tier_stats": dict(tier_stats),
            "calibration": {
                "slope": CALIB_SLOPE,
                "intercept": CALIB_INTERCEPT,
                "n_models": CALIB_N,
                "r_squared": CALIB_R2,
            },
            "results": results,
        }
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w") as f:
            json.dump(output, f, indent=2, ensure_ascii=False)
        print(f"  Results saved to {args.output}")


if __name__ == "__main__":
    main()
